# Generated by Django 5.0.6 on 2024-06-27 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movies', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('censor_info', models.CharField(max_length=30)),
                ('no_of_seasons', models.CharField(max_length=30)),
                ('quality', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('running_time', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('delete_status', models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1)),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ImageField(upload_to='media/')),
                ('genere', models.ManyToManyField(related_name='accociated_genere', to='Movies.genere')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_name1', to='series.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_name2', to='series.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asscociated_person', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('link', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_name', to='series.series')),
            ],
        ),
    ]
