# Generated by Django 5.0.6 on 2024-06-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_alter_seriescomments_owner_alter_seriesreview_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriescomments',
            name='delete_status',
            field=models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1),
        ),
        migrations.AddField(
            model_name='seriesreview',
            name='delete_status',
            field=models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1),
        ),
    ]
