# Generated by Django 5.0.6 on 2024-07-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_alter_seriescomments_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesreview',
            name='description',
        ),
        migrations.AddField(
            model_name='seriesreview',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seriesreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
