# Generated by Django 5.0.6 on 2024-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_remove_seriesreview_description_seriesreview_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriescomments',
            name='comment',
            field=models.CharField(max_length=250),
        ),
    ]
