# Generated by Django 5.0.6 on 2024-06-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_moviecomments_delete_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genere',
            field=models.ManyToManyField(related_name='genere_name', to='Movies.genere'),
        ),
    ]
