# Generated by Django 5.0.6 on 2024-07-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_alter_movies_genere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
